/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/hexagon.glb -o src/components/Hexagon.jsx -r public
*/

import { useFrame } from "@react-three/fiber";
import { RigidBody } from "@react-three/rapier";
import React, { useEffect, useMemo, useRef, useState } from "react";
import { Color } from "three";
import { MathUtils, randFloat, randInt } from "three/src/math/MathUtils.js";
import { useAudioManager } from "../hooks/useAudioManager";

const TIME_AFTER_HIT = 600;
const HEX_SIZE = 1.1;
const HEX_HEIGHT = 0.4;

export function Hexagon({ color, onHit, hit, ...props }) {
  const { playAudio } = useAudioManager();
  const hexagonMaterial = useRef();

  const [disabled, setDisabled] = useState(false);
  const randomizedColor = useMemo(() => {
    const alteredColor = new Color(color);
    alteredColor.multiplyScalar(randFloat(0.5, 1.2));
    return alteredColor;
  }, [color]);

  useFrame((_, delta) => {
    if (hit && !disabled && hexagonMaterial.current) {
      hexagonMaterial.current.opacity = MathUtils.lerp(
        hexagonMaterial.current.opacity,
        0,
        delta * 1.2
      );
    }
  });

  useEffect(() => {
    if (hit) {
      setTimeout(() => {
        setDisabled(true);
        if (playAudio) playAudio(`Pop${randInt(1, 5)}`);
      }, TIME_AFTER_HIT);
    }
  }, [hit]);

  if (disabled) {
    return null;
  }

  return (
    <RigidBody
      {...props}
      type={"fixed"}
      name="hexagon"
      colliders="hull"
      onCollisionEnter={(e) => {
        if (e.other.rigidBodyObject && e.other.rigidBodyObject.name === "player") {
          onHit();
        }
      }}
    >
      {/* Simple cylinder as hex platform - no external model needed */}
      <mesh>
        <cylinderGeometry args={[HEX_SIZE, HEX_SIZE, HEX_HEIGHT, 6]} />
        <meshStandardMaterial
          ref={hexagonMaterial}
          color={hit ? "#ff6600" : randomizedColor}
          transparent={!!hit}
        />
      </mesh>
    </RigidBody>
  );
}
